record encryption
ellie/atuin pull request #1058
Opened 2023-06-18 14:46 UTC by conradludgate

2023-06-20 15:31 UTC, mercxry commented on atuin-client/src/record/encryption.rs
> +If they never leave the hardward, then encrypting large amounts of data means giving them the data and waiting.
Small typo ;)
```suggestion
If they never leave the hardware, then encrypting large amounts of data means giving them the data and waiting.
```

2023-06-20 15:44 UTC, mercxry commented on atuin-client/src/record/encryption.rs
> +A HSM (Hardward security module) provider, eg AWS, Azure, GCP, or even a physical device like a yubikey
Wouldn't wanna leave for the Hacktoberfest 🤣
```suggestion
A HSM (Hardware Security Module) provider, eg: AWS, Azure, GCP, or even a physical device like a YubiKey
```

2023-06-21 07:43 UTC, ellie requested changes
This is great, thank you! Just the spelling error and we're good

2023-06-21 07:43 UTC, ellie commented on atuin-common/src/record.rs
> +pub struct AdditonalData<'a> {
```suggestion
pub struct AdditionalData<'a> {
```

sorry 😭

2023-06-26 06:52 UTC, ellie approved these changes

2023-06-26 06:52 UTC, merged