run shellcheck
ellie/atuin pull request #97
Opened 2021-05-09 22:28 UTC by ismith

Fixes #64

2021-05-09 22:37 UTC, conradludgate commented on .github/workflows/shellcheck.yml
> +  pull_request:
```suggestion
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
```

2021-05-09 22:52 UTC, ismith commented
I'm not sure why it's still not picking up the new action. Any ideas, @conradludgate ?

2021-05-09 22:55 UTC, conradludgate commented
https://github.com/ellie/atuin/actions/runs/826177834/workflow

2021-05-09 22:56 UTC, ismith commented
D'oh! That's it!

2021-05-09 23:23 UTC, ismith commented
Ready for review. One thing to put eyes on: this https://github.com/ellie/atuin/pull/97/commits/92a74ea5550dcfb16078a2e94461c0b3d44fecf2 is fine, right? We're just checking for a status code there?

2021-05-10 00:17 UTC, bl-ue commented
Shellcheck + zsh: https://github.com/koalaman/shellcheck/issues/809

2021-05-10 06:21 UTC, conradludgate commented
Do you think you could add a comment to every ignore line?

2021-05-12 20:45 UTC, ellie commented on src/shell/atuin.bash
> +export ATUIN_SESSION=
```suggestion
export ATUIN_SESSION
```

2021-05-12 20:46 UTC, ellie requested changes
Thanks for this! I've just got one small suggestion (as it looks like the = [should not be there](https://github.com/koalaman/shellcheck/wiki/SC2155)?)

Happy to merge once this is done :blush:

2021-05-13 01:42 UTC, ismith commented
Thanks for catching that! I also resolved the merge conflict in install.sh.

2021-05-14 07:30 UTC, ellie commented
Thank you! :rocket:

2021-05-14 07:31 UTC, ellie approved these changes

2021-05-14 07:31 UTC, merged

2021-12-19 05:01 UTC, SuperSandro2000 commented on install.sh
> +# Use of single quotes around $() is intentional here
Yes, they are. We want the string as is into the rc file.